### ISSUE TITLE
COMP 424 - A1 Question 1

### ISSUE THREAD

**Issue by ben-jamming** [ben-jamming/COMP-424#1]
**Description**:
For all of the following, answer the analytical question using a similar level of rigor as was provided in the class slides. Always assume positive costs for every operation. Reason about the most general case you can imagine, but if you require them, write out your assumptions at the top of your solution.

**Tasks**:
- [x] Describe a state space in which iterative deepening search performs much worse than depth-first search (for example, O(n^2) vs O(n)).
Prove each of the following statements, or give a counterexample:
- [x] Breadth-first search is a special case of uniform-cost search
- [x] Best-first search is optimal in the case where we have a perfect heuristic (i.e., ℎ(n) = ℎ∗(n), the true cost to the closest goal state).
- [x] Suppose there is a unique optimal solution. Then, A* search with a perfect heuristic will never expand nodes that are not in the path of the optimal solution
- [x] A* search with a heuristic which is admissible but not consistent is complete.
