### ISSUE TITLE
COMP 424 - A1 Question 2

### ISSUE THREAD

**Issue by ben-jamming** [ben-jamming/COMP-424#2]
**Description**:

![Image](https://github.com/ben-jamming/COMP-424/assets/53016294/a97ff8a3-6e1f-4090-8459-8d0eccb4a202)

**Tasks**:
- [ ] Formulate this problem as a CSP. List the variables, their domains, and the constraints. Draw the constraint graph of a general 2x2 Sudoku game (that is, do not consider the pattern of filled in numbers in the example).
- [ ] Show the first ten steps of backtracking search on the sample provided, where you order the variables in increasing order first by row, then by column (in English reading-order), and the values from lowest to highest (1 to 4). Recall that backtracking search uses a depth-first strategy to expand the search tree.
- [ ] Show the first ten steps of backtracking search on this problem with **one-step forward checking**, with the same variable ordering.
